version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jikanzo-postgres-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: jikanzo_docker_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata-local:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jikanzo-redis-local
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata-local:/data

volumes:
  pgdata-local:
  redisdata-local:
